const PROJECTS_DATA = [
  {
    title: 'Shoprrr',
    description: 'An E-commerce Application For Buying Cotton Products.',
    github: 'https://github.com/Mukhammadr1zo/shoprr',
    about:
      'Shoprrr is an e-commerce platform catered towards giving the best and fast experience for customers to buy cotton products, we call it a frictionless process from start to finish.',
    link: 'https://shoprrr.netlify.com',
    imageUrl: 'https://i.ibb.co/T0XwFsQ/Screen-Recording-2020-05-06-at-3.gif',
    type: ['project'],
    technologies: ['React', 'Redux', 'Javascript'],
  },
  {
    title: 'TSTU Alumni',
    github: 'https://github.com/Mukhammadr1zo/',
    description: 'Alumni of Tashkent State Transport University',
    about: 'Alumni of Tashkent State Transport University',
    link: 'http://alumni.tstu.uz/',
    imageUrl: 'https://i.ibb.co/7jJn1pv/image.png',
    type: ['project', 'open-source'],
    technologies: ['React', 'WordPress', 'SQL'],
  },
  {
    title: 'Movies',
    github: 'https://github.com/Mukhammadr1zo/Movies-App',
    description: 'A list of new films and serials',
    about: 'Such kinds of movies are ready to watch',
    link: 'https://movies-me.netlify.app/',
    imageUrl: 'https://i.ibb.co/r6Djx86/films.png',
    type: ['project', 'open-source'],
    technologies: ['React', 'Javascript', 'themoviedb'],
  },
  {
    title: 'Resume Builder',
    github: 'https://github.com/Mukhammadr1zo/Movies-App',
    description: 'Resume builder in uzbek language.',
    about: 'You can create a new resume or you can edit your own',
    link: 'https://tstu-resume-builder.netlify.app/',
    imageUrl: 'https://i.ibb.co/5n46Vhh/image.png',
    type: ['project', 'open-source'],
    technologies: ['Next.js', 'Javascript', 'Tailwind CSS', 'Node.js'],
  },
  {
    title: 'HU One Collection',
    github: 'https://github.com/rakhimovsh/textile_ui',
    description: 'HU One Collection Clothes Shop',
    about: 'HU One Collection Clothes Shop',
    link: 'https://textile-ui.netlify.app/',
    imageUrl: 'https://i.ibb.co/VJJHfBj/image.png',
    type: ['project', 'open-source'],
    technologies: ['React.js', 'Javascript', 'AOS', 'Ant Design'],
  },
  {
    title: 'Barber Shop',
    github: 'https://github.com/Mukhammadr1zo/Movies-App',
    description: 'Barber Shop`s website',
    about: 'Barber Shop`s website',
    link: 'https://anvarbeyba.netlify.app/',
    imageUrl: 'https://i.ibb.co/ZzSsmjb/image.png',
    type: ['project', 'open-source'],
    technologies: ['React', 'Javascript', 'Ant Design', 'Styled Compnents'],
  },
];

export default PROJECTS_DATA;
